// Per-metric presentation: icon + a clear, unambiguous tooltip description.
// Keyed by the raw WiNet-S i18n key so it stays stable across firmware label changes.
export const METRIC_META = {
  I18N_COMMON_TOTAL_ACTIVE_POWER: {
    icon: 'bolt',
    desc: 'AC active power the inverter is generating right now and feeding to the house/grid. This IS your live solar output (measured).',
  },
  I18N_COMMON_TOTAL_DCPOWER: {
    icon: 'panel',
    desc: 'Total DC power drawn from the solar panels before inverter conversion losses.',
  },
  I18N_COMMON_TOTAL_REACTIVE_POWER: {
    icon: 'wave',
    desc: 'Reactive power exchanged with the grid (kvar). Does no real work; relates to voltage support.',
  },
  I18N_COMMON_TOTAL_APPARENT_POWER: {
    icon: 'bolt',
    desc: 'Apparent power = vector sum of active and reactive power (kVA).',
  },
  I18N_COMMON_MAXIMUM_APPARENT_POWER_SIWHFGQY: {
    icon: 'gauge',
    desc: 'Rated maximum apparent power of this inverter (nameplate ceiling, 10 kVA).',
  },
  I18N_COMMON_TOTAL_POWER_FACTOR: {
    icon: 'gauge',
    desc: 'Power factor (-1..1): ratio of active to apparent power. 1.0 = purely active.',
  },
  I18N_COMMON_DAILY_POWER_YIELD: {
    icon: 'calendar',
    desc: 'Energy generated since midnight today (kWh).',
  },
  I18N_COMMON_TOTAL_YIELD: {
    icon: 'sigma',
    desc: 'Lifetime energy generated by this inverter since installation (kWh).',
  },
  I18N_COMMON_TOTAL_GRID_RUNNING_TIME: {
    icon: 'clock',
    desc: 'Cumulative hours the inverter has spent feeding the grid.',
  },
  I18N_COMMON_GRID_FREQUENCY: {
    icon: 'wave',
    desc: 'Measured grid frequency (Hz). Nominal is 50 Hz here; deviations indicate grid stress.',
  },
  I18N_COMMONUA: {
    icon: 'plug',
    desc: 'Phase A grid voltage at the inverter terminals (V).',
  },
  I18N_COMMON_FRAGMENT_RUN_TYPE1: {
    icon: 'plug',
    desc: 'Phase A grid current (A).',
  },
  I18N_COMMON_BUS_VOLTAGE: {
    icon: 'chip',
    desc: 'Internal DC bus voltage inside the inverter (V).',
  },
  I18N_COMMON_SQUARE_ARRAY_INSULATION_IMPEDANCE: {
    icon: 'shield',
    desc: 'Insulation resistance of the PV array to ground (kΩ). High = healthy; low warns of insulation faults.',
  },
  I18N_COMMON_AIR_TEM_INSIDE_MACHINE: {
    icon: 'thermometer',
    desc: 'Air temperature measured inside the inverter enclosure (℃).',
  },
  I18N_COMMON_RUNNING_STATE: {
    icon: 'gauge',
    desc: 'Operating state of the inverter (Standby at night / no sun, Running when generating).',
  },
}

const PHASE_V = 'Per-phase grid voltage (A/B/C). This SG10RS is single-phase, so B and C read "--".'
const PHASE_A = 'Per-phase grid current (A/B/C).'
export const CONFIG_KEY_META = {
  I18N_CONFIG_KEY_1003332: { icon: 'plug', desc: PHASE_V + ' — Phase A voltage.' },
  I18N_CONFIG_KEY_1003334: { icon: 'plug', desc: PHASE_V + ' — Phase B voltage.' },
  I18N_CONFIG_KEY_1003336: { icon: 'plug', desc: PHASE_V + ' — Phase C voltage.' },
  I18N_CONFIG_KEY_1003331: { icon: 'plug', desc: PHASE_A + ' — Phase A current.' },
  I18N_CONFIG_KEY_1003333: { icon: 'plug', desc: PHASE_A + ' — Phase B current.' },
  I18N_CONFIG_KEY_1003335: { icon: 'plug', desc: PHASE_A + ' — Phase C current.' },
}

export function metaFor(key) {
  return METRIC_META[key] || CONFIG_KEY_META[key] || { icon: 'gauge', desc: 'Raw inverter reading.' }
}
